### ISSUE TITLE
When tap to run a test, have NPE error for `_GroupInfoSectionBuilder._buildHeader`

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_convenient_test#135]

**Comment by fzyzcjy** [comment]
```

======== Exception caught by flutter_mobx ==========================================================
The following MobXCaughtException was thrown From reaction of Observer
Observer constructed from: _GroupInfoSectionBuilder._buildHeader (package:convenient_test_manager/components/home_page/group_entry_info_widget.dart:68:12) of type StatelessObserverElement.:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      GroupEntryInfo.traverse (package:convenient_test_common_dart/src/suite_info.dart:90:34)
#1      _GroupInfoSectionBuilder._buildGroupStat (package:convenient_test_manager/components/home_page/group_entry_info_widget.dart:114:10)
#2      _GroupInfoSectionBuilder._buildHeader.<anonymous closure> (package:convenient_test_manager/components/home_page/group_entry_info_widget.dart:100:20)
#3      Observer.build (package:flutter_mobx/src/observer.dart:51:48)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4827:28)
#5      ObserverElementMixin.build.<anonymous closure> (package:flutter_mobx/src/observer_widget_mixin.dart:120:21)
#6      ReactiveContext.trackDerivation (package:mobx/src/core/context.dart:256:20)
#7      ReactionImpl.track (package:mobx/src/core/reaction.dart:84:14)

**Comment by fzyzcjy** [comment]
Exception: cannot find entry for childEntryId=358422044225377 (this.id=358422044225376, this.name=simple test group, suiteInfo.entryMap=[358426803469696, 358426803666308, 358426803666306, 358426803666304, 358426803371392, 358426803502464, 358426803600768, 358426803600769, 358426803600770, 358426803600771, 358426803600772, 358426803600773, 358426803600774, 358426803666305, 358426803666307, 358426803666309])

**Comment by fzyzcjy** [comment]
<details>

flutter: 2022-05-07T14:25:17.710437Z|debug|ConvenientTestManagerService|getWorkerCurrentRunConfig ans=integrationTest: {[NL]  reportSuiteInfo: true[NL]  executionFilter: {[NL]    filterNameRegex: ^some other test group empty test$[NL]    strategy: {[NL]      allMatch: {[NL]      }[NL]    }[NL]  }[NL]  defaultRetryCount: 1[NL]}[NL]
flutter: 2022-05-07T14:25:18.055704Z|debug|ReportHandlerService|handleSetUpAll 
flutter: 2022-05-07T14:25:18.061177Z|debug|ReportHandlerService|handleReportSuiteInfo called groupId: 358426803371392[NL]groups: {[NL]  id: 358426803469696[NL]  name: simple test group[NL]  parentId: 358426803371392[NL]  entryIds: 358426803502464[NL]  entryIds: 358426803600768[NL]  entryIds: 358426803600769[NL]  entryIds: 358426803600770[NL]  entryIds: 358426803600771[NL]  entryIds: 358426803600772[NL]  entryIds: 358426803600773[NL]  entryIds: 358426803600774[NL]}[NL]groups: {[NL]  id: 358426803666308[NL]  name: some other test group sample sub-group sample sub-sub-group[NL]  parentId: 358426803666306[NL]  entryIds: 358426803666309[NL]}[NL]groups: {[NL]  id: 358426803666306[NL]  name: some other test group sample sub-group[NL]  parentId: 358426803666304[NL]  entryIds: 358426803666307[NL]  entryIds:
flutter:  358426803666308[NL]}[NL]groups: {[NL]  id: 358426803666304[NL]  name: some other test group[NL]  parentId: 358426803371392[NL]  entryIds: 358426803666305[NL]  entryIds: 358426803666306[NL]}[NL]groups: {[NL]  id: 358426803371392[NL]  name: [NL]  parentId: -1[NL]  entryIds: 358426803469696[NL]  entryIds: 358426803666304[NL]}[NL]tests: {[NL]  id: 358426803502464[NL]  name: simple test group choose some fruits[NL]  parentId: 358426803469696[NL]}[NL]tests: {[NL]  id: 358426803600768[NL]  name: simple test group deliberately failing test[NL]  parentId: 358426803469696[NL]}[NL]tests: {[NL]  id: 358426803600769[NL]  name: simple test group deliberately flaky test[NL]  parentId: 358426803469696[NL]}[NL]tests: {[NL]  id: 358426803600770[NL]  name: simple test group navigation[NL]  parentId: 3584268
flutter: 03469696[NL]}[NL]tests: {[NL]  id: 358426803600771[NL]  name: simple test group custom logging and snapshotting[NL]  parentId: 358426803469696[NL]}[NL]tests: {[NL]  id: 358426803600772[NL]  name: simple test group custom commands[NL]  parentId: 358426803469696[NL]}[NL]tests: {[NL]  id: 358426803600773[NL]  name: simple test group sections[NL]  parentId: 358426803469696[NL]}[NL]tests: {[NL]  id: 358426803600774[NL]  name: simple test group timer page[NL]  parentId: 358426803469696[NL]}[NL]tests: {[NL]  id: 358426803666305[NL]  name: some other test group empty test[NL]  parentId: 358426803666304[NL]}[NL]tests: {[NL]  id: 358426803666307[NL]  name: some other test group sample sub-group another empty test[NL]  parentId: 358426803666306[NL]}[NL]tests: {[NL]  id: 358426803666309[NL]  name: som
flutter: e other test group sample sub-group sample sub-sub-group yet another empty test[NL]  parentId: 358426803666308[NL]}[NL]
flutter: 2022-05-07T14:25:18.061743Z|debug|ReportHandlerService|reset cache since see SuiteInfo
flutter: 2022-05-07T14:25:18.062382Z|debug|MiscDartService|clearAll
flutter: 2022-05-07T14:25:18.073611Z|debug|ReportHandlerService|handleReportRunnerStateChange called testName=some other test group empty test state=status: running[NL]result: success[NL]
flutter: 2022-05-07T14:25:18.078108Z|debug|VideoRecorderStore|startRecord call ScreenVideoRecorderService begin
flutter: 2022-05-07T14:25:18.080517Z|info|ScreenVideoRecorderServiceIosSimulator|startRecord begin /Users/tom/Library/Caches/ConvenientTest_Video_20220507_102518.mov
flutter: 2022-05-07T14:25:18.185783Z|debug|VideoRecorderStore|startRecord call ScreenVideoRecorderService en

</details>

**Comment by fzyzcjy** [comment]
know the problem: the whole tree is replaced...

**Comment by fzyzcjy** [comment]
no errors now.
