### ISSUE TITLE
exception when finished running tests in isolation mode

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_convenient_test#145]

**Comment by fzyzcjy** [comment]
flutter: 2022-05-08T02:15:56.550436Z|warn|ConvenientTestMain|ConvenientTest captured error (via runZonedGuarded). type(e)=RangeError exception=RangeError (index): Invalid value: Only valid value is 0: 1 stackTrace=#0      List.[] (dart:core-patch/growable_array.dart:281:36)[NL]#1      _ExecutionFilterResolver.resolve (package:convenient_test_dev/src/support/executor.dart:105:59)[NL]#2      ConvenientTestExecutor.execute.<anonymous closure> (package:convenient_test_dev/src/support/executor.dart:30:61)[NL]#3      runTestsInDeclarer.<anonymous closure> (package:convenient_test_dev/src/third_party/my_test_compat.dart:37:17)[NL]#4      runTestsInDeclarer.<anonymous closure> (package:convenient_test_dev/src/third_party/my_test_compat.dart:34:31)[NL]#5      _rootRun (dart:async/zone.dart:1426:13)[NL]#6
flutter:    _CustomZone.run (dart:async/zone.dart:1328:19)[NL]#7      _runZoned (dart:async/zone.dart:1861:10)[NL]#8      runZoned (dart:async/zone.dart:1783:10)[NL]#9      Invoker.guard (package:test_api/src/backend/invoker.dart:154:7)[NL]#10
