### ISSUE TITLE
explicitly show which golden test fails, by marking them on LogEntry (or throwing exceptions at the locations expectLater fails)

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_convenient_test#179]

**Comment by fzyzcjy** [comment]
```
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following assertion was thrown while running async test code:
flutter: Golden "goldens/deliberately_failed_golden.png": Pixel test failed, 0.58% diff detected.
flutter: Failure feedback can be found at
flutter: /Users/tom/QAPMain/TomLib/flutter_convenient_test/packages/convenient_test/example/integration_test/failures
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      LocalFileComparator.compare (package:flutter_test/src/_goldens_io.dart:100:7)
flutter: <asynchronous suspension>
flutter: #1      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:101:30)
flutter: <asynchronous suspension>
flutter: #2      LiveTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:1598:14)
flutter: <asynchronous suspension>
flutter: #3      _expectWithRetry (package:convenient_test_dev/src/functions/command.dart:90:11)
flutter: <asynchronous suspension>
flutter: #4      ExtTCommand.should (package:convenient_test_dev/src/functions/command.dart:32:5)
flutter: <asynchronous suspension>
flutter: #5      main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/tom/QAPMain/TomLib/flutter_convenient_test/packages/convenient_test/example/integration_test/main_test.dart:77:9)
flutter: <asynchronous suspension>
flutter: #6      tTestWidgets.<anonymous closure>.<anonymous closure> (package:convenient_test_dev/src/functions/core.dart:170:7)
flutter: <asynchronous suspension>
flutter: #7      ConvenientTest.withActiveInstance (package:convenient_test_dev/src/functions/core.dart:43:7)
flutter: <asynchronous suspension>
flutter: #8      tTestWidgets.<anonymous closure> (package:convenient_test_dev/src/functions/core.dart:164:23)
flutter: <asynchronous suspension>
flutter: #9      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:15)
flutter: <asynchronous suspension>
flutter: #10     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:806:5)
flutter: <asynchronous suspension>
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by fzyzcjy** [comment]
seems because of this?

![image](https://user-images.githubusercontent.com/5236035/167856747-8cff25d5-1341-482d-b760-f288a7645c3d.png)

**Comment by fzyzcjy** [comment]
```
  /// Returns the exception most recently caught by the Flutter framework.
  ///
  /// Call this if you expect an exception during a test. If an exception is
  /// thrown and this is not called, then the exception is rethrown when
  /// the [testWidgets] call completes.

  dynamic takeException() {
```

**Comment by fzyzcjy** [comment]
## Next: deal with error message

**Comment by fzyzcjy** [comment]
pr made

* https://github.com/flutter/flutter/pull/103486

**Comment by fzyzcjy** [comment]
![image](https://user-images.githubusercontent.com/5236035/167861464-55241153-3255-4a90-bdda-4992825a7a49.png)
