### ISSUE TITLE
for updateGoldens, give a GUI to check git diff

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_convenient_test#201]

**Comment by fzyzcjy** [comment]
sample ui: https://github.com/flutter/flutter/pull/101036

**Comment by fzyzcjy** [comment]
how to know dirty files?

**Comment by fzyzcjy** [comment]
git diff --name-only

**Comment by fzyzcjy** [comment]
https://stackoverflow.com/questions/610208/how-to-retrieve-a-single-file-from-a-specific-revision-in-git

**Comment by fzyzcjy** [comment]
git show HEAD:aaa.png> ~/temp/0000.png

**Comment by fzyzcjy** [comment]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): The provided value "/Users/tom/QAPMain/Development/blob" is not the root of a git directory
#0      GitDir.fromExisting (package:git/src/git_dir.dart:414:5)
<asynchronous suspension>
#1      _GoldenDiffPageStore._calcGitFolderInfo (package:convenient_test_manager/stores/golden_diff_page_store.dart:41:20)
<asynchronous suspension>
#2      _GoldenDiffPageStore._syncGitFolderInfoFromRepo (package:convenient_test_manager/stores/golden_diff_page_store.dart:34:21)
<asynchronous suspension>

**Comment by fzyzcjy** [comment]
```
flutter: 2022-05-13T13:05:28.459247Z|debug|GoldenDiffPageStore|calcGitFolderInfo step get file content
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FormatException: Unexpected extension byte (at offset 0)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1859:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _rootRunUnary (dart:async/zone.dart:1434:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#11     _StreamController._add (dart:async/stream_controller.dart:648:7)
#12     _StreamController.add (dart:async/stream_controller.dart:596:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2314:41)
#14     _rootRunUnary (dart:async/zone.dart:1442:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#20     _StreamController._add (dart:async/stream_controller.dart:648:7)
#21     _StreamController.add (dart:async/stream_controller.dart:596:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1839:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Comment by fzyzcjy** [comment]
![image](https://user-images.githubusercontent.com/5236035/168289731-2585847e-ad40-4ac0-a4f3-e3024d8de0a0.png)

**Comment by fzyzcjy** [comment]
make it horizontal scrollable?

**Comment by fzyzcjy** [comment]
basic mode done.
