### ISSUE TITLE
Loading big report fails

### ISSUE THREAD

**Issue by gnunicorn** [fzyzcjy/flutter_convenient_test#368]
**Describe the bug**
Trying to load a big report file fails (shown on the CI) and the UI is just stuck empty.

**To Reproduce**
1. [Download this large report](https://github.com/acterglobal/a3/actions/runs/8007132858/artifacts/1267104232) we ran with the CI
2. extract the ZIP
3. Open the Convenient Manager
4. Attempt to load the report from the UI
5. See error on the CLI:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly
in the middle of a field. This could either mean that the input
has been truncated or that an embedded message misreported its
own length.

Note that the buffer containing the message has 328221025 bytes, but
CodedBufferReader was allowed to parse only 67108864 bytes.

#0      CodedBufferReader._throwTruncatedMessageError (package:protobuf/src/protobuf/coded_buffer_reader.dart:34:7)
#1      CodedBufferReader.readMessage (package:protobuf/src/protobuf/coded_buffer_reader.dart:110:7)
#2      _mergeFromCodedBufferReader (package:protobuf/src/protobuf/coded_buffer.dart:186:15)
#3      GeneratedMessage.mergeFromBuffer (package:protobuf/src/protobuf/generated_message.dart:192:5)
#4      new ReportCollection.fromBuffer (package:convenient_test_common_dart/src/protobuf/convenient_test.pb.dart:38:17)
#5      MiscDartService.readReportFromFile (package:convenient_test_manager_dart/services/misc_dart_service.dart:53:47)
<asynchronous suspension>
#6      MiscFlutterService.pickFileAndReadReport (package:convenient_test_manager/services/misc_flutter_service.dart:35:5)
<asynchronous suspension>

```

**Expected behavior**

It works, I suppose. Maybe by reading the file in a stream or in chunks rather than it failing ...

**Screenshots**

![grafik](https://github.com/fzyzcjy/flutter_convenient_test/assets/40496/36553779-e547-4a6c-ba75-1c532e01211e)

**Desktop (please complete the following information):**
 - OS: Linux Manjaro (Arch)

**Comment by fzyzcjy** [comment]
> Note that the buffer containing the message has 328221025 bytes, but
CodedBufferReader was allowed to parse only 67108864 bytes.

Hmm... Looks like protobuf's reader does not like that big size. 

https://pub.dev/documentation/protobuf/latest/protobuf/CodedBufferReader-class.html Maybe we just need to do a simple change: e.g. `CodedBufferReader(sizeLimit: 1000000000)`.

**Comment by gnunicorn** [comment]
Got a PR to fix it.

Though loading large files like that is pretty slow: like multi-minutes on modern hardware,  where the screen just sits there and CPU usage is pretty high (I had to decrease the log-level as well or the debug print would simply be too much ...)

**Comment by fzyzcjy** [comment]
> Though loading large files like that is pretty slow: like multi-minutes on modern hardware, where the screen just sits there and CPU usage is pretty high (I had to decrease the log-level as well or the debug print would simply be too much ...)

Hmm... Maybe we can use another isolate to load it, for example.
