### ISSUE TITLE
Unable to run convenient_test

### ISSUE THREAD

**Issue by TimeLord2010** [fzyzcjy/flutter_convenient_test#373]
**Describe the bug**
I'm getting this error while trying to run the app with covenient_test:

```
Unhandled Exception: Null check operator used on a null value
#0      SpyDeclarer.withSpy
```

Here is the full logs:
```
sudo flutter run /Users/viniciuscotta/Work/Grav/gepe_frontend/test/ui/pages/login_screen_integration_test.dart --host-vmservice-port 9753 --disable-service-auth-codes --dart-define CONVENIENT_TEST_APP_CODE_DIR=/Users/viniciuscotta/Work/Grav/gepe_frontend
Password:
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Connected devices:
macOS (desktop) • macos  • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.57

Checking for wireless devices...

[1]: macOS (macos)
[2]: Chrome (chrome)
Please choose one (or "q" to quit): 1
Launching test/ui/pages/login_screen_integration_test.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-0011682910C0291E }
{ platform:macOS, arch:x86_64, id:00008103-0011682910C0291E }
Building macOS application...                                           
2024-02-27 11:51:55.058 gepe_frontend[36344:230220] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
2024-02-27 11:51:55.329 gepe_frontend[36344:230220] TISFileInterrogator updateSystemInputSources false but old data invalid: currentCacheHeaderPtr nonNULL? 0, ->cacheFormatVersion 0, ->magicCookie 00000000, inputSourceTableCountSys 0
Keyboard Layouts: duplicate keyboard layout identifier -17410.
Keyboard Layouts: keyboard layout identifier -17410 has been replaced with -28673.
Keyboard Layouts: duplicate keyboard layout identifier -30769.
Keyboard Layouts: keyboard layout identifier -30769 has been replaced with -28674.
Keyboard Layouts: duplicate keyboard layout identifier -14934.
Keyboard Layouts: keyboard layout identifier -14934 has been replaced with -28675.
flutter: 2024-02-27T14:51:55.577010Z|info|WorkerReportSaverServiceSaveToLocal|will save report to path=/tmp/ConvenientTestWidgetTest/WIDGET-TEST-20240227-115155-206.bin
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      SpyDeclarer.withSpy (package:convenient_test_dev/src/support/spy_declarer.dart:19:46)
#1      convenientTestEntrypointWhenEnvWidget (package:convenient_test_dev/src/functions/entrypoint_env_widget.dart:18:41)
#2      convenientTestMain (package:convenient_test_dev/src/functions/entrypoint.dart:24:13)
#3      main (file:///Users/viniciuscotta/Work/Grav/gepe_frontend/test/ui/pages/login_screen_integration_test.dart:13:9)
#4      _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

Syncing files to device macOS...                                   162ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
```

**Desktop:**
 - OS: MacOS M1
 - Version 14.3.1

**Comment by fzyzcjy** [comment]
Hi, could you please show your code (the login_screen_integration_test.dart)? For example, without more information, I guess this may because the test infra is somehow not started.

**Comment by TimeLord2010** [comment]
Here:

```dart
import 'package:convenient_test_dev/convenient_test_dev.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:gepe_frontend/main.dart' as app;
import 'package:gepe_frontend/main.dart';
import 'package:gepe_frontend/ui/components/atoms/gepe_text_field.dart';
import 'package:gepe_frontend/ui/components/molecules/login/login/login_inputs.dart';
import 'package:gepe_frontend/ui/components/organisms/login/login_foreground.dart';
import 'package:gepe_frontend/ui/components/organisms/login/login_foreground/fields_container.dart';
import 'package:gepe_frontend/ui/components/organisms/login/login_foreground/fields_container/login_fields.dart';

void main() async {
  await convenientTestMain(
    MyConvenientTestSlot(),
    () {
      group('Login screen', () {
        tTestWidgets('Has text fields', (t) async {
          debugPrint('Searching for LoginForeground');
          expect(find.byType(LoginForeground), findsOneWidget);
          expect(find.byType(FieldsContainer), findsOneWidget);
          expect(find.byType(LoginFields), findsOneWidget);
          expect(find.byType(LoginInputs), findsOneWidget);
          expect(find.byType(GepeTextField), findsNWidgets(2));
          expect(
            find.descendant(
              of: find.byKey(const ValueKey('email')),
              matching: find.byType(GepeTextField),
              matchRoot: true,
            ),
            findsOneWidget,
          );
        });
      });
    },
    executionEnv: ExecutionEnv.widgetTest,
  );
}

class MyConvenientTestSlot extends ConvenientTestSlot {
  @override
  Future<void> appMain(AppMainExecuteMode mode) async => app.main();

  @override
  BuildContext? getNavContext(ConvenientTest t) => MyApp.navigatorKey.currentContext;
}

// flutter run /Users/viniciuscotta/Work/Grav/gepe_frontend/test/ui/pages/login_screen_integration_test.dart --host-vmservice-port 9753 --disable-service-auth-codes --dart-define CONVENIENT_TEST_APP_CODE_DIR=/Users/viniciuscotta/Work/Grav/gepe_frontend
```

In case this is a infra issue, what should I do?

**Comment by fzyzcjy** [comment]
Firstly, `executionEnv: ExecutionEnv.widgetTest` -- maybe it is `.deviceTest`?

Secondly, if it does not work, maybe firstly try the example https://github.com/fzyzcjy/flutter_convenient_test/tree/2dfee8760b820e3951de7dceb4edc96c14cc6980/packages/convenient_test/example.

**Comment by AngDrew** [comment]
have you wrap the app (inside runApp function) with `ConvenientTestWrapperWidget`? @TimeLord2010

**Comment by TimeLord2010** [comment]
@AngDrew Yes. I'm still having the same error.

**Comment by TimeLord2010** [comment]
Update to the other commented who recommended .deviceTest:

Whenever I use the default option, I get multiple times this error:
```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following StateError was thrown while handling a pointer data packet:
flutter: Bad state: No element
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      Iterable.firstWhere (dart:core/iterable.dart:702:5)
flutter: #1      LiveTestWidgetsFlutterBinding.handlePointerEvent (package:flutter_test/src/binding.dart:1927:53)
flutter: #2      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
flutter: #3      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
flutter: #7      _invoke1 (dart:ui/hooks.dart:330:10)
flutter: #8      PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:429:7)
flutter: #9      _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
flutter: (elided 3 frames from dart:async)
```

**Comment by fzyzcjy** [comment]
> Whenever I use the default option, I get multiple times this error

Does it happen when you click the app, or when you do not click it but it auto has this error?

Btw, does

> Secondly, if it does not work, maybe firstly try the example [2dfee87/packages/convenient_test/example](https://github.com/fzyzcjy/flutter_convenient_test/tree/2dfee8760b820e3951de7dceb4edc96c14cc6980/packages/convenient_test/example).

this suggestion work?
