### ISSUE TITLE
reportRunnerMessage has error for tearDownAll

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_convenient_test#43]

**Comment by fzyzcjy** [comment]
flutter: 2022-05-04T07:22:32.240682Z|error|ConvenientTestManagerService|error when handling grpc requests. error=Exception: need to implicitly create test entry, but no testGroupId provided name=(tearDownAll) stack=#0      _OrganizationStore.testEntryNameToId (package:convenient_test_manager/stores/organization_store.dart:49:7)[NL]#1      ConvenientTestManagerService.reportRunnerMessage (package:convenient_test_manager/services/convenient_test_manager_service.dart:74:50)[NL]#2      ConvenientTestManagerServiceBase.reportRunnerMessage_Pre (package:convenient_test_common/src/protobuf/convenient_test.pbgrpc.dart:155:12)[NL]<asynchronous suspension>[NL]#3      new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:218:17)[NL]<asynchronous suspension>[NL]
