### ISSUE TITLE
take a video (not only screenshots) for the whole testing process, easing debugging, especially some transitioning problems

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_convenient_test#60]
## Method A: take a png file for each frame, and assemble them into videos in Manager

drawback: each png is at least (?) 50KB. even only for 30fps, 1second=1.5MB, 1minute=90MB, 10minute=900MB. unacceptable.
in addition, converting png into videos can be CPU consuming.

## Method B: use the builtin "screen recording" functionality of ios/android

problem: ios simulator does not seem to support this?

## Method C: use a screen recorder on the *host* machine to really capture the screen into a video (Cypress also does this)

problem: it is an extra component

## (chosen) Method D: for ios simulators / android, xcode has a command to capture `.mov` videos

https://stackoverflow.com/questions/25797990/capture-ios-simulator-video-for-app-preview

android has similar https://stackoverflow.com/questions/31547350/how-to-record-screen-with-android-studio

**Comment by fzyzcjy** [comment]
pending on #66

**Comment by fzyzcjy** [comment]
- [ ] manually record a video using cli to see what is happening
- [ ] create a layer of "video recorder"
- [ ] determine when can this layer be executed, and isolate errors if it happens
- [ ] implement ios video recorder
- [ ] execute the recorder when appropreate
- [ ] test it

**Comment by fzyzcjy** [comment]
ctrl-c to stop it.

looks good.

(base) ➜  dev git:(master) xcrun simctl io booted recordVideo ~/temp/a.mov
Recording started
^CWrote video to: /Users/tom/temp/a.mov

**Comment by fzyzcjy** [comment]
Question: when to start this recorder?

Question: when to stop it?

**Comment by fzyzcjy** [comment]
what type of log?

LogEntry?
not good. it should be a global thing.

**Comment by fzyzcjy** [comment]
now test it

**Comment by fzyzcjy** [comment]
flutter: 2022-05-05T02:14:28.651871Z|debug|VideoRecorderServiceIosSimulator|[STDERR] xcrun: error: cannot be used within an App Sandbox.[NL]

**Comment by fzyzcjy** [comment]
attempt:

```
Future<void> main() async {
  final result = await Process.run('ls', ['-al']);
  print('result ${result.exitCode} ${result.stdout} ${result.stderr}');
  return;
```

sounds good

**Comment by fzyzcjy** [comment]
```
Future<void> main() async {
  final result = await Process.run('xcrun', []);
  print('result ${result.exitCode} ${result.stdout} ${result.stderr}');
  return;
```

flutter: result 1  xcrun: error: cannot be used within an App Sandbox.

**Comment by fzyzcjy** [comment]
https://developer.apple.com/forums/thread/73554

**Comment by fzyzcjy** [comment]
https://developer.apple.com/forums/thread/26389?answerId=89866022#89866022

**Comment by fzyzcjy** [comment]
https://stackoverflow.com/questions/26082365/any-possible-way-to-run-the-clang-compiler-from-a-sandboxed-app

**Comment by fzyzcjy** [comment]
or, can we disable app sandbox?

**Comment by fzyzcjy** [comment]
flutter: 2022-05-05T02:27:16.241961Z|debug|VideoRecorderServiceIosSimulator|[STDERR] Wrote video to: /Users/tom/Library/Caches/ConvenientTest_Video_20220505_102708.mov[NL]
flutter: 2022-05-05T02:27:16.246517Z|info|VideoRecorderServiceIosSimulator|stopRecord exitCode=0

i see the video, looks good

**Comment by fzyzcjy** [comment]
now naively display the video

**Comment by fzyzcjy** [comment]
now test it

**Comment by fzyzcjy** [comment]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      VideoPlayerApi.initialize (package:video_player_platform_interface/messages.dart:156:7)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:181:7)
<asynchronous suspension>
#1      MethodChannelVideoPlayer.create (package:video_player_platform_interface/method_channel_video_player.dart:54:37)
<asynchronous suspension>
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:356:19)
<asynchronous suspension>
#3      _WrappedVideoPlayerState._init (package:convenient_test_manager/components/home_page/video_panel.dart:77:5)
<asynchronous suspension>

**Comment by fzyzcjy** [comment]
it does not support desktop...

![image](https://user-images.githubusercontent.com/5236035/166856817-3f31ff7a-c57b-4e8d-8285-c1fd7eed2196.png)
![image](https://user-images.githubusercontent.com/5236035/166856819-91cc0a94-ee48-4c41-bd3c-6d7e202af56b.png)

**Comment by fzyzcjy** [comment]
https://stackoverflow.com/questions/56206307/video-player-for-web-mobile-and-desktop-applications-in-flutter

**Comment by fzyzcjy** [comment]
https://pub.dev/packages/dart_vlc

**Comment by fzyzcjy** [comment]
dyld: Library not loaded: @loader_path/../Frameworks/VLCKit.framework/Versions/A/VLCKit
  Referenced from: /Users/tom/QAPMain/TomLib/flutter_convenient_test/packages/convenient_test_manager/build/macos/Build/Products/Debug/convenient_test_manager.app/Contents/Frameworks/dart_vlc.framework/Versions/A/dart_vlc
  Reason: image not found

**Comment by fzyzcjy** [comment]
https://pub.dev/packages/dart_vlc

follow the "setup" section

**Comment by fzyzcjy** [comment]
just upgrade cmake, then ok

**Comment by fzyzcjy** [comment]
![image](https://user-images.githubusercontent.com/5236035/166858278-e51b11e7-6109-4c72-ba63-c02dfd889a8a.png)
